# basic headers
title: Test blog with Jekyll
author: Alexis Gillett
email: # leaving blank for now
description: Trial blog using GitHub pages.

# social links
twitter_username: AlexisJGillett
github_username:  ajg54

# other settings
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
plugins:
 - jekyll-feed
