title: Test blog with Jekyll
author: Alexis Gillett
email: # leaving black until now
description: > # this means to ignore newlines until "baseurl:"
  Trial blog using GitHub pages.
# social links
twitter_username: AlexisJGillett
github_username:  ajg54

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
