# basic details
title: Test blog with Jekyll
author: Alexis Gillett
email: alexisjgillett@gmail.com
description: Trial blog using GitHub pages.

# social links
bsky_username: alexisgillett
github_username:  ajg54

# other settings
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
plugins:
 - jekyll-feed
exclude: [_posts/archive/]
